apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-storage
  namespace: platform
  labels:
    app: longhorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn
  template:
    metadata:
      labels:
        app: longhorn
    spec:
      containers:
        - name: longhorn-storage
          image: busybox:latest
          command: ["sh", "-c", "echo Longhorn Local Storage Provisioned && sleep infinity"]
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "50m"
