apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-operator
  namespace: platform
  labels:
    app: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda
  template:
    metadata:
      labels:
        app: keda
    spec:
      containers:
        - name: keda-operator
          image: ghcr.io/kedacore/keda:2.14.0
          command:
            - /keda
          env:
            - name: WATCH_NAMESPACE
              value: "platform"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
