apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flowise
  namespace: gitops
spec:
  project: default
  source:
    repoURL: "https://github.com/usmanaliclouds-jpg/avi-repo"
    targetRevision: HEAD
    path: apps/flowise
  destination:
    server: "https://kubernetes.default.svc"
    namespace: automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
