apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: platform
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.16.2
          args:
            - server
            - -dev
            - -dev-listen-address=0.0.0.0:8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root"
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: "0.0.0.0:8200"
          ports:
            - containerPort: 8200
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: platform
  labels:
    app: vault
spec:
  type: ClusterIP
  ports:
    - port: 8200
      targetPort: 8200
      name: http
  selector:
    app: vault
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: platform
type: Opaque
stringData:
  token: "root"
